Repository AY2223S1-CS2103T-T15-1/tp, pull requests merged in 2022-10, with the labels that each got.

#63 Refactor person class
  src/main/java/coydir/MainApp.java
  src/main/java/coydir/commons/core/LogsCenter.java
  src/main/java/coydir/logic/commands/AddCommand.java
  src/main/java/coydir/logic/commands/EditCommand.java
  src/main/java/coydir/logic/parser/AddCommandParser.java
  src/main/java/coydir/logic/parser/CliSyntax.java
  src/main/java/coydir/logic/parser/EditCommandParser.java
  src/main/java/coydir/logic/parser/ParserUtil.java
  src/main/java/coydir/model/person/Address.java
  src/main/java/coydir/model/person/EmployeeId.java
  src/main/java/coydir/model/person/Person.java
  src/main/java/coydir/model/person/Position.java
  src/main/java/coydir/model/util/SampleDataUtil.java
  src/main/java/coydir/storage/JsonAdaptedPerson.java
  src/main/java/coydir/ui/HelpWindow.java
  src/main/java/coydir/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/coydir/logic/LogicManagerTest.java
  src/test/java/coydir/logic/commands/CommandTestUtil.java
  src/test/java/coydir/logic/commands/EditCommandTest.java
  src/test/java/coydir/logic/commands/EditPersonDescriptorTest.java
  src/test/java/coydir/logic/parser/AddCommandParserTest.java
  src/test/java/coydir/logic/parser/AddressBookParserTest.java
  src/test/java/coydir/logic/parser/EditCommandParserTest.java
  src/test/java/coydir/logic/parser/ParserUtilTest.java
  src/test/java/coydir/model/person/EmployeeIdTest.java
  src/test/java/coydir/model/person/PositionTest.java
  src/test/java/coydir/storage/JsonAdaptedPersonTest.java
  src/test/java/coydir/testutil/EditPersonDescriptorBuilder.java
  src/test/java/coydir/testutil/PersonBuilder.java
  src/test/java/coydir/testutil/PersonUtil.java
  src/test/java/coydir/testutil/TypicalPersons.java
Labels: priority.high, type.refactor

#64 Refactor delete function
  src/main/java/coydir/logic/commands/DeleteCommand.java
  src/main/java/coydir/logic/parser/DeleteCommandParser.java
  src/main/java/coydir/logic/parser/ParserUtil.java
  src/test/java/coydir/logic/commands/DeleteCommandTest.java
  src/test/java/coydir/logic/parser/AddressBookParserTest.java
  src/test/java/coydir/logic/parser/DeleteCommandParserTest.java
  src/test/java/coydir/testutil/TypicalIndexes.java
Labels: priority.high, type.Task

#66 Fix invalid command GUI
  src/main/java/coydir/commons/core/Messages.java
  src/main/java/coydir/logic/parser/AddressBookParser.java
  src/main/java/coydir/ui/CommandBox.java
  src/test/java/coydir/logic/LogicManagerTest.java
  src/test/java/coydir/logic/commands/DeleteCommandTest.java
  src/test/java/coydir/logic/parser/AddressBookParserTest.java
  src/test/java/coydir/logic/parser/DeleteCommandParserTest.java
Labels: priority.medium, type.Task

#71 Implement Add Function and Varargs
  docs/images/Ui.png
  src/main/java/coydir/logic/commands/AddCommand.java
  src/main/java/coydir/logic/parser/AddCommandParser.java
  src/main/java/coydir/model/person/Person.java
  src/test/java/coydir/logic/commands/CommandTestUtil.java
  src/test/java/coydir/logic/parser/AddCommandParserTest.java
  src/test/java/coydir/testutil/TypicalPersons.java
Labels: priority.high, type.Story

#82 Implements `view` command and the ability to display more detailed information
  src/main/java/coydir/logic/commands/CommandResult.java
  src/main/java/coydir/logic/commands/ViewCommand.java
  src/main/java/coydir/logic/parser/AddressBookParser.java
  src/main/java/coydir/logic/parser/ViewCommandParser.java
  src/main/java/coydir/model/person/UniquePersonList.java
  src/main/java/coydir/ui/MainWindow.java
  src/main/java/coydir/ui/PersonCard.java
  src/main/java/coydir/ui/PersonInfo.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonInfo.fxml
  src/main/resources/view/PersonListCard.fxml
Labels: priority.Medium, type.Ui

#83 Update help command
  src/main/java/coydir/MainApp.java
  src/main/java/coydir/ui/CommandFormat.java
  src/main/java/coydir/ui/HelpWindow.java
  src/main/java/coydir/ui/UiManager.java
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/HelpWindow.fxml
Labels: priority.Medium, type.Task, type.Ui

#84 Refactor-Remove placeholders for optional fields, replace with 'N/A' value instead
  src/main/java/coydir/logic/parser/AddCommandParser.java
  src/main/java/coydir/model/person/Address.java
  src/main/java/coydir/model/person/Email.java
  src/main/java/coydir/model/person/Phone.java
  src/test/java/coydir/testutil/PersonBuilder.java
  src/test/java/coydir/testutil/TypicalPersons.java
Labels: priority.High, type.Refactor

#88 Update User Guide
  docs/UserGuide.md
  src/main/java/coydir/commons/core/Messages.java
  src/main/java/coydir/model/person/UniquePersonList.java
Labels: priority.High, type.Documentation, type.Task

#92 Ui enhancement and implement clickable personListPanel
  src/main/java/coydir/ui/HelpWindow.java
  src/main/java/coydir/ui/MainWindow.java
  src/main/java/coydir/ui/PersonListPanel.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/HelpWindow.fxml
  src/main/resources/view/LightTheme.css
  src/main/resources/view/PersonInfo.fxml
Labels: priority.Medium, type.Enhancement

#91 Feature batch add function
  src/main/java/coydir/logic/commands/AddCommand.java
  src/main/java/coydir/logic/commands/BatchAddCommand.java
  src/main/java/coydir/logic/parser/BatchAddCommandParser.java
  src/main/java/coydir/logic/parser/CliSyntax.java
  src/main/java/coydir/logic/parser/DatabaseParser.java
  src/main/java/coydir/logic/parser/ParserUtil.java
  src/test/data/BatchAddTest/BatchAddDuplicatePerson.csv
  src/test/data/BatchAddTest/BatchAddSuccess.csv
  src/test/java/coydir/logic/commands/AddCommandIntegrationTest.java
  src/test/java/coydir/logic/commands/AddCommandTest.java
  src/test/java/coydir/logic/commands/BatchAddCommandTest.java
  src/test/java/coydir/testutil/TypicalPersons.java
Labels: priority.High, type.Story, type.Task

#109 Fix incorrect id update after duplicate
  src/main/java/coydir/logic/commands/AddCommand.java
Labels: priority.High, type.Bug

#110 Enable assertion update gitignore
  .gitignore
  README.md
  build.gradle
  docs/UserGuide.md
  docs/index.md
Labels: priority.High

#113 Add BatchAdd documentation to DG
  docs/DeveloperGuide.md
Labels: type.Documentation

#115 Update Developer's Guide for Add Feature
  docs/DeveloperGuide.md
  docs/images/AddCommandUML.png
Labels: priority.High, type.Task

#116 Add find command to dev guide
  docs/DeveloperGuide.md
Labels: priority.Medium, type.Documentation

#118 update dg for view feature
  docs/DeveloperGuide.md
  docs/images/ViewCommandUML.png
Labels: priority.Medium, type.Documentation

#119 Feat department field
  src/main/java/coydir/commons/core/Messages.java
  src/main/java/coydir/logic/commands/AddCommand.java
  src/main/java/coydir/logic/commands/EditCommand.java
  src/main/java/coydir/logic/parser/AddCommandParser.java
  src/main/java/coydir/logic/parser/CliSyntax.java
  src/main/java/coydir/logic/parser/EditCommandParser.java
  src/main/java/coydir/logic/parser/ParserUtil.java
  src/main/java/coydir/model/person/Department.java
  src/main/java/coydir/model/person/Person.java
  src/main/java/coydir/model/person/Position.java
  src/main/java/coydir/model/person/UniquePersonList.java
  src/main/java/coydir/model/util/SampleDataUtil.java
  src/main/java/coydir/storage/JsonAdaptedPerson.java
  src/main/java/coydir/ui/PersonCard.java
  src/main/java/coydir/ui/PersonInfo.java
  src/main/resources/view/PersonInfo.fxml
  src/test/data/BatchAddTest/BatchAddDuplicatePerson.csv
  src/test/data/BatchAddTest/BatchAddSuccess.csv
  src/test/data/JsonDatabaseStorageTest/invalidAndValidPersonDatabase.json
  src/test/data/JsonDatabaseStorageTest/invalidPersonDatabase.json
  src/test/data/JsonSerializableDatabaseTest/duplicatePersonDatabase.json
  src/test/data/JsonSerializableDatabaseTest/invalidPersonDatabase.json
  src/test/data/JsonSerializableDatabaseTest/typicalPersonsDatabase.json
  src/test/java/coydir/logic/LogicManagerTest.java
  src/test/java/coydir/logic/commands/CommandTestUtil.java
  src/test/java/coydir/logic/commands/EditPersonDescriptorTest.java
  src/test/java/coydir/logic/parser/AddCommandParserTest.java
  src/test/java/coydir/logic/parser/EditCommandParserTest.java
  src/test/java/coydir/logic/parser/ParserUtilTest.java
  src/test/java/coydir/model/person/DepartmentTest.java
  src/test/java/coydir/model/person/PersonTest.java
  src/test/java/coydir/model/person/PositionTest.java
  src/test/java/coydir/storage/JsonAdaptedPersonTest.java
  src/test/java/coydir/testutil/EditPersonDescriptorBuilder.java
  src/test/java/coydir/testutil/PersonBuilder.java
  src/test/java/coydir/testutil/PersonUtil.java
  src/test/java/coydir/testutil/TypicalIndexes.java
  src/test/java/coydir/testutil/TypicalPersons.java
Labels: priority.High, type.Task

#121 Update user guide with leave functions.
  docs/UserGuide.md
Labels: priority.High, type.Documentation

#123 Create add and remove leave commands
  src/main/java/coydir/commons/core/Messages.java
  src/main/java/coydir/logic/commands/AddLeaveCommand.java
  src/main/java/coydir/logic/commands/DeleteCommand.java
  src/main/java/coydir/logic/commands/DeleteLeaveCommand.java
  src/main/java/coydir/logic/parser/AddLeaveCommandParser.java
  src/main/java/coydir/logic/parser/CliSyntax.java
  src/main/java/coydir/logic/parser/DatabaseParser.java
  src/main/java/coydir/logic/parser/DeleteLeaveCommandParser.java
  src/main/java/coydir/logic/parser/ParserUtil.java
  src/main/java/coydir/model/person/Leave.java
  src/main/java/coydir/model/person/Person.java
  src/main/java/coydir/storage/JsonAdaptedLeave.java
Labels: priority.High, type.Task

#122 Implement Rating class field and performanceHistory tracking
  src/main/java/coydir/logic/commands/AddLeaveCommand.java
  src/main/java/coydir/logic/commands/EditCommand.java
  src/main/java/coydir/logic/commands/RateCommand.java
  src/main/java/coydir/logic/parser/AddCommandParser.java
  src/main/java/coydir/logic/parser/CliSyntax.java
  src/main/java/coydir/logic/parser/DatabaseParser.java
  src/main/java/coydir/logic/parser/ParserUtil.java
  src/main/java/coydir/logic/parser/RateCommandParser.java
  src/main/java/coydir/model/person/Leave.java
  src/main/java/coydir/model/person/Person.java
  src/main/java/coydir/model/person/Rating.java
  src/main/java/coydir/model/util/SampleDataUtil.java
  src/main/java/coydir/storage/JsonAdaptedPerson.java
  src/main/java/coydir/storage/JsonAdaptedRating.java
  src/main/java/coydir/ui/PersonInfo.java
  src/main/resources/view/PersonInfo.fxml
  src/test/data/JsonSerializableDatabaseTest/duplicatePersonDatabase.json
  src/test/data/JsonSerializableDatabaseTest/invalidPersonDatabase.json
  src/test/data/JsonSerializableDatabaseTest/typicalPersonsDatabase.json
  src/test/java/coydir/logic/commands/EditCommandTest.java
  src/test/java/coydir/storage/JsonAdaptedPersonTest.java
  src/test/java/coydir/testutil/PersonBuilder.java
  src/test/java/coydir/testutil/TypicalPersons.java
Labels: priority.High, type.Task

#125 User Guide update find
  docs/UserGuide.md
Labels: type.Documentation

#130 Fix bug for edit person command
  src/main/java/coydir/logic/commands/EditCommand.java
  src/main/java/coydir/model/person/Person.java
Labels: type.Bug

#133 UI enhancement bug fix
  src/main/java/coydir/commons/core/GuiSettings.java
  src/main/java/coydir/logic/commands/AddCommand.java
  src/main/java/coydir/logic/commands/DeleteLeaveCommand.java
  src/main/java/coydir/model/person/Leave.java
  src/main/java/coydir/ui/MainWindow.java
  src/main/java/coydir/ui/PersonInfo.java
  src/main/resources/images/logo.png
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonInfo.fxml
Labels: priority.High, type.Bug

#140 Bug fix leave table
  src/main/java/coydir/model/person/Person.java
Labels: priority.High, type.Bug, type.Flaw

#143 Performance graph feature
  src/main/java/coydir/ui/PersonInfo.java
  src/main/java/coydir/ui/UiManager.java
  src/main/resources/images/Coydir_Logo.png
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonInfo.fxml
Labels: priority.High, type.Task

#144 add view department command
  src/main/java/coydir/commons/core/Messages.java
  src/main/java/coydir/logic/Logic.java
  src/main/java/coydir/logic/LogicManager.java
  src/main/java/coydir/logic/commands/CommandResult.java
  src/main/java/coydir/logic/commands/ViewDepartmentCommand.java
  src/main/java/coydir/logic/parser/DatabaseParser.java
  src/main/java/coydir/logic/parser/ViewDepartmentCommandParser.java
  src/main/java/coydir/model/person/Person.java
  src/main/java/coydir/ui/DepartmentInfo.java
  src/main/java/coydir/ui/HomePanel.java
  src/main/java/coydir/ui/MainWindow.java
  src/main/java/coydir/ui/PersonInfo.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/DepartmentInfo.fxml
  src/main/resources/view/HomePanel.fxml
Labels: priority.High, type.Story

#145 Update user guide shawn
  docs/UserGuide.md
  src/main/java/coydir/ui/PersonInfo.java
  src/main/resources/view/PersonInfo.fxml
Labels: priority.High, type.Documentation

#150 Fix personinfo autoupdate
  docs/images/Ui.png
  src/main/java/coydir/MainApp.java
  src/main/java/coydir/logic/commands/CommandResult.java
  src/main/java/coydir/logic/commands/DeleteCommand.java
  src/main/java/coydir/logic/commands/EditCommand.java
  src/main/java/coydir/logic/commands/ViewCommand.java
  src/main/java/coydir/ui/HomePanel.java
  src/main/java/coydir/ui/MainWindow.java
  src/main/java/coydir/ui/PersonInfo.java
  src/main/resources/images/logo.png
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/HomePanel.fxml
  src/main/resources/view/LightTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonInfo.fxml
  src/test/java/coydir/logic/commands/EditCommandTest.java
Labels: priority.High, type.Bug, type.Flaw

#151 Fix jar file
  src/main/java/coydir/commons/core/GuiSettings.java
  src/main/java/coydir/ui/HomePanel.java
  src/main/java/coydir/ui/MainWindow.java
  src/main/java/coydir/ui/PersonCard.java
  src/main/java/coydir/ui/PersonInfo.java
Labels: priority.High, type.Bug

#218 Ug restructure features
  README.md
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/Coydir_Logo.png
  docs/images/diagrams/AddCommandUML.png
  docs/images/diagrams/ArchitectureDiagram.png
  docs/images/diagrams/ArchitectureSequenceDiagram.png
  docs/images/diagrams/BetterModelClassDiagram.png
  docs/images/diagrams/CommitActivityDiagram.png
  docs/images/diagrams/ComponentManagers.png
  docs/images/diagrams/DeleteCommandUML.png
  docs/images/diagrams/DeleteSequenceDiagram.png
  docs/images/diagrams/LogicClassDiagram.png
  docs/images/diagrams/LogicStorageDIP.png
  docs/images/diagrams/ModelClassDiagram.png
  docs/images/diagrams/ParserClasses.png
  docs/images/diagrams/StorageClassDiagram.png
  docs/images/diagrams/UiClassDiagram.png
  docs/images/diagrams/UndoRedoState0.png
  docs/images/diagrams/UndoRedoState1.png
  docs/images/diagrams/UndoRedoState2.png
  docs/images/diagrams/UndoRedoState3.png
  docs/images/diagrams/UndoRedoState4.png
  docs/images/diagrams/UndoRedoState5.png
  docs/images/diagrams/UndoSequenceDiagram.png
  docs/images/diagrams/ViewCommandUML.png
  docs/images/findAlexDavidResult.png
  docs/images/helpMessage.png
  docs/images/johndoe.png
  docs/images/profiles/chao890.png
  docs/images/profiles/kevinchangjk.png
  docs/images/profiles/kok-je.png
  docs/images/profiles/ngshijun.png
  docs/images/profiles/prit3010.png
  docs/images/request_access.png
  docs/images/ui-screenshots/Ui.png
  docs/index.md
  docs/tutorials/TracingCode.md
Labels: priority.High, type.Documentation

#160 Refactor person fields
  src/main/java/coydir/commons/core/Messages.java
  src/main/java/coydir/commons/exceptions/DataConversionException.java
  src/main/java/coydir/commons/util/ConfigUtil.java
  src/main/java/coydir/logic/commands/AddCommand.java
  src/main/java/coydir/logic/commands/AddLeaveCommand.java
  src/main/java/coydir/logic/commands/BatchAddCommand.java
  src/main/java/coydir/logic/commands/ClearCommand.java
  src/main/java/coydir/logic/commands/CommandResult.java
  src/main/java/coydir/logic/commands/DeleteCommand.java
  src/main/java/coydir/logic/commands/DeleteLeaveCommand.java
  src/main/java/coydir/logic/commands/FindCommand.java
  src/main/java/coydir/logic/commands/HelpCommand.java
  src/main/java/coydir/logic/commands/ListCommand.java
  src/main/java/coydir/logic/commands/RateCommand.java
  src/main/java/coydir/logic/commands/ViewCommand.java
  src/main/java/coydir/logic/commands/ViewDepartmentCommand.java
  src/main/java/coydir/logic/parser/AddCommandParser.java
  src/main/java/coydir/logic/parser/AddLeaveCommandParser.java
  src/main/java/coydir/logic/parser/RateCommandParser.java
  src/main/java/coydir/model/person/Address.java
  src/main/java/coydir/model/person/Email.java
  src/main/java/coydir/model/person/Leave.java
  src/main/java/coydir/model/person/Phone.java
  src/main/java/coydir/model/person/Rating.java
  src/main/java/coydir/storage/JsonAdaptedPerson.java
  src/main/java/coydir/storage/JsonAdaptedRating.java
  src/main/java/coydir/ui/DepartmentInfo.java
  src/main/java/coydir/ui/HomePanel.java
  src/main/java/coydir/ui/MainWindow.java
  src/main/java/coydir/ui/PersonCard.java
  src/main/java/coydir/ui/PersonInfo.java
  src/test/java/coydir/logic/commands/FindCommandTest.java
Labels: priority.Low, type.Enhancement

#221 Update quickstart,leave section and delete section for user guide
  docs/UserGuide.md
  docs/images/ui-screenshots/addLeaveCommandOutcome.png
  docs/images/ui-screenshots/deleteLeaveCommandOutcome.png
Labels: priority.High

#226 update ug for view, list and viewdepartment
  docs/UserGuide.md
  docs/images/ui-screenshots/view_department.png
Labels: type.Documentation

#227 Fixed UG for overall descriptions and rate, changed aesthetics for html page
  docs/UserGuide.md
  docs/_sass/minima/custom-styles.scss
  docs/_sass/minima/custom-variables.scss
  docs/_sass/minima/initialize.scss
Labels: priority.High, type.Documentation

#223 UG: Update find, edit, help commands
  docs/UserGuide.md
  docs/images/chao890.png
  docs/images/kevinchangjk.png
  docs/images/kok-je.png
  docs/images/ngshijun.png
  docs/images/prit3010.png
  docs/images/ui-screenshots/edit-example1.png
  docs/images/ui-screenshots/find-example.png
  docs/images/ui-screenshots/find-example2.png
Labels: priority.High, type.Documentation

#224 Add Labelled Images and more information about the User Interface
  docs/UserGuide.md
  docs/images/ui-screenshots/Command.png
  docs/images/ui-screenshots/Employee Info Panel.png
  docs/images/ui-screenshots/Employee List Panel.png
  docs/images/ui-screenshots/Labelled GUI.png
  docs/images/ui-screenshots/Toolbar.png
Labels: priority.High, type.Documentation

#225 Update batch-add clear exit ug
  docs/UserGuide.md
  docs/images/batch-add-images/BatchAddSuccess.png
  docs/images/batch-add-images/DuplicateEmployee.png
  docs/images/batch-add-images/Incorrect Format.png
  docs/images/batch-add-images/SampleExcel.png
  docs/images/batch-add-images/movingFile.png
  docs/images/batch-add-images/sampleCSV.png
  docs/images/ui-screenshots/Clear.png
  src/main/java/coydir/logic/commands/BatchAddCommand.java
Labels: priority.High, type.Documentation

#228 Update ug colorscheme
  docs/_sass/minima/custom-styles.scss
  docs/_sass/minima/custom-variables.scss
Labels: priority.Low

#229 Fix info blocks
  docs/UserGuide.md
  docs/images/ui-screenshots/Employee-Info-Panel.png
  docs/images/ui-screenshots/Employee-List-Panel.png
  docs/images/ui-screenshots/Labelled-GUI.png
Labels: priority.Medium, type.Documentation
