Repository AY2223S1-CS2103T-T15-1/tp, pull requests merged in 2022-11, with the labels that each got.

#230 Fix resetting employee id bug after clearing
  src/main/java/coydir/logic/commands/ClearCommand.java
Labels: priority.High, type.Bug

#231 Update UG details for rate command
  docs/UserGuide.md
Labels: priority.Medium, type.Documentation

#235 PED bug fixes and small user guide changes
  docs/UserGuide.md
  src/main/java/coydir/model/person/Leave.java
Labels: priority.High, type.Documentation

#233 Update help window
  docs/UserGuide.md
  src/main/java/coydir/ui/CommandFormat.java
  src/main/java/coydir/ui/HelpWindow.java
  src/main/resources/view/HelpWindow.fxml
Labels: priority.Medium, type.Documentation, type.Bug

#232 Fix add find bugs
  src/main/java/coydir/logic/commands/FindCommand.java
  src/main/java/coydir/logic/parser/AddCommandParser.java
  src/main/java/coydir/logic/parser/AddLeaveCommandParser.java
  src/main/java/coydir/logic/parser/DeleteCommandParser.java
  src/main/java/coydir/logic/parser/DeleteLeaveCommandParser.java
  src/main/java/coydir/logic/parser/EditCommandParser.java
  src/main/java/coydir/logic/parser/ParserUtil.java
  src/main/java/coydir/logic/parser/RateCommandParser.java
  src/main/java/coydir/ui/MainWindow.java
  src/test/java/coydir/logic/LogicManagerTest.java
  src/test/java/coydir/logic/commands/CommandTestUtil.java
  src/test/java/coydir/logic/commands/EditCommandTest.java
  src/test/java/coydir/logic/commands/FindCommandTest.java
  src/test/java/coydir/logic/parser/AddCommandParserTest.java
  src/test/java/coydir/logic/parser/DatabaseParserTest.java
  src/test/java/coydir/logic/parser/ParserUtilTest.java
  src/test/java/coydir/testutil/PersonBuilder.java
Labels: priority.Medium, type.Bug

#238 Update help window
  src/main/resources/view/HelpWindow.fxml
Labels: type.Bug

#242 Fixed Rating bugs
  docs/UserGuide.md
  docs/images/ui-screenshots/performance-history-graph.jpg
  src/main/java/coydir/logic/commands/RateCommand.java
  src/main/java/coydir/model/person/Rating.java
  src/main/java/coydir/ui/PersonInfo.java
Labels: priority.High, type.Documentation, type.Task, type.Bug

#244 Kevin ppp
  docs/team/kevinchangjk.md
Labels: priority.Medium, type.Documentation

#243 Update PPP
  docs/team/chao890.md
Labels: type.Documentation

#246 Update catchy phrase intro hook
  docs/UserGuide.md
  docs/_sass/minima/custom-styles.scss
Labels: priority.Medium, type.Documentation

#247 Update PPP-Shawn
  docs/UserGuide.md
  docs/team/chao890.md
  docs/team/kok-je.md
  docs/team/prit3010.md
Labels: priority.High, type.Documentation

#248 Fix duplicate employee
  src/main/java/coydir/model/person/EmployeeId.java
  src/main/java/coydir/storage/JsonAdaptedPerson.java
  src/main/java/coydir/ui/MainWindow.java
  src/test/data/JsonSerializableDatabaseTest/duplicatePersonDatabase.json
  src/test/data/JsonSerializableDatabaseTest/invalidPersonDatabase.json
  src/test/data/JsonSerializableDatabaseTest/typicalPersonsDatabase.json
  src/test/java/coydir/logic/commands/CommandTestUtil.java
  src/test/java/coydir/logic/parser/AddCommandParserTest.java
  src/test/java/coydir/model/person/EmployeeIdTest.java
  src/test/java/coydir/storage/JsonAdaptedPersonTest.java
  src/test/java/coydir/storage/JsonDatabaseStorageTest.java
  src/test/java/coydir/storage/JsonSerializableDatabaseTest.java
  src/test/java/coydir/storage/StorageManagerTest.java
  src/test/java/coydir/testutil/TestUtil.java
  src/test/java/coydir/testutil/TypicalPersons.java
Labels: priority.Medium, type.Bug

#249 Fix images filepath
  docs/AboutUs.md
  docs/UserGuide.md
  docs/images/Sample_CSV.png
  docs/images/Ui.png
Labels: priority.Low, type.Bug

#251 Add tests for leave related commands
  build.gradle
  src/test/java/coydir/logic/commands/AddLeaveCommandTest.java
  src/test/java/coydir/logic/commands/DeleteLeaveCommandTest.java
  src/test/java/coydir/logic/parser/AddLeaveCommandParserTest.java
  src/test/java/coydir/logic/parser/DeleteLeaveCommandParserTest.java
  src/test/java/coydir/testutil/PersonBuilder.java
  src/test/java/coydir/testutil/TypicalPersons.java
Labels: priority.High

#254 Rate test cases
  docs/UserGuide.md
  docs/team/chao890.md
  docs/team/kok-je.md
  src/main/java/coydir/model/person/Rating.java
  src/test/java/coydir/model/person/RatingTest.java
Labels: priority.Medium, type.Enhancement, type.Task

#250 Dg update find
  docs/DeveloperGuide.md
  docs/diagrams/FindSequenceDiagram.puml
  docs/images/diagrams/FindCommandUML.png
  docs/team/kevinchangjk.md
Labels: priority.Medium, type.Documentation

#252 update PPP
  docs/team/ngshijun.md
Labels: type.Documentation

#257 Implemented more test cases for RateCommand
  src/test/java/coydir/logic/commands/RateCommandTest.java
  src/test/java/coydir/logic/parser/DatabaseParserTest.java
  src/test/java/coydir/logic/parser/RateCommandParserTest.java
  src/test/java/coydir/testutil/PersonBuilder.java
Labels: priority.Medium, type.Enhancement, type.Task

#253 Upgrade test for employee ID and find
  src/main/java/coydir/logic/parser/FindCommandParser.java
  src/main/java/coydir/model/person/EmployeeId.java
  src/test/java/coydir/logic/parser/FindCommandParserTest.java
  src/test/java/coydir/model/person/EmployeeIdTest.java
  src/test/java/coydir/model/person/PersonMatchesKeywordsPredicateTest.java
  src/test/java/coydir/model/person/PositionTest.java
  src/test/java/coydir/testutil/TypicalPersons.java
Labels: priority.Medium

#258 DG updates
  docs/DeveloperGuide.md
  docs/diagrams/AddLeaveSequenceDiagram.puml
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/DeleteLeaveSequenceDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/images/diagrams/AddLeaveCommandUML.png
  docs/images/diagrams/DeleteCommandUML.png
  docs/images/diagrams/DeleteLeaveCommandUML.png
  docs/images/diagrams/DeleteSequenceDiagram.png
Labels: priority.High, type.Documentation

#260 Dg update appendix
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/FindSequenceDiagram.puml
  docs/images/Ui.png
  docs/images/diagrams/FindCommandUML.png
  docs/index.md
  src/main/java/coydir/logic/commands/AddCommand.java
Labels: priority.Medium, type.Documentation

#262 Fix random bugs
  docs/UserGuide.md
  src/main/java/coydir/commons/core/Messages.java
  src/main/java/coydir/logic/commands/AddLeaveCommand.java
  src/main/java/coydir/logic/commands/DeleteCommand.java
  src/main/java/coydir/logic/commands/DeleteLeaveCommand.java
  src/main/java/coydir/logic/commands/EditCommand.java
  src/main/java/coydir/logic/commands/RateCommand.java
  src/main/java/coydir/logic/commands/ViewCommand.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/LightTheme.css
  src/test/java/coydir/logic/LogicManagerTest.java
  src/test/java/coydir/logic/commands/AddLeaveCommandTest.java
  src/test/java/coydir/logic/commands/DeleteCommandTest.java
  src/test/java/coydir/logic/commands/DeleteLeaveCommandTest.java
  src/test/java/coydir/logic/commands/EditCommandTest.java
  src/test/java/coydir/logic/commands/RateCommandTest.java
Labels: priority.Medium, type.Documentation, type.Bug

#261 Refactor developer guide
  docs/DeveloperGuide.md
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/images/diagrams/LogicClassDiagram.png
  docs/images/diagrams/ModelClassDiagram.png
  docs/images/diagrams/StorageClassDiagram.png
  docs/team/chao890.md
Labels: priority.High, type.Documentation

#263 Dg update misc
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/_sass/minima/_base.scss
  docs/diagrams/AddLeaveSequenceDiagram.puml
  docs/images/diagrams/AddLeaveCommandUML.png
Labels: priority.Medium, type.Documentation

#264 Update DG for RateCommand
  docs/DeveloperGuide.md
  docs/diagrams/AddSequenceDiagram.puml
  docs/diagrams/RateSequenceDiagram.puml
  docs/images/diagrams/AddCommandUML.png
  docs/images/diagrams/RateCommandUML.png
Labels: priority.High, type.Documentation

#269 Updated PPP to fit 2 pages
  docs/team/kok-je.md
Labels: priority.High, type.Documentation

#270 Fix image alignment
  README.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/_sass/minima/_base.scss
  docs/_sass/minima/custom-styles.scss
  docs/diagrams/BatchAdd.puml
  docs/diagrams/ParserClasses.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/images/diagrams/BatchAddUML.png
  docs/images/diagrams/ParserClasses.png
  docs/images/diagrams/StorageClassDiagram.png
Labels: priority.Medium, type.Documentation

#272 Fix RateCommand getPersonList bug
  src/main/java/coydir/logic/commands/RateCommand.java
Labels: priority.Medium, type.Enhancement, type.Bug

#271 Ppp update shawn
  docs/team/kok-je.md
Labels: priority.High, type.Documentation

#276 Update ug and dg
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: priority.Medium, type.Documentation

#277 Fix heading issue
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Documentation

#279 Ug refactor features
  docs/UserGuide.md
  docs/images/ui-screenshots/department-leave.png
  docs/images/ui-screenshots/help-window.png
  docs/images/ui-screenshots/view-employee-leave.png
Labels: priority.Medium, type.Documentation

#280 Update UG
  docs/UserGuide.md
  docs/_sass/minima/custom-styles.scss
  docs/_sass/minima/initialize.scss
  docs/images/Coydir.png
  docs/images/Ui.png
  docs/images/ui-screenshots/Labelled-GUI.png
  docs/images/ui-screenshots/Toolbar.png
Labels: type.Documentation, type.Enhancement

#284 Fix ug final
  docs/UserGuide.md
  docs/images/ui-screenshots/Employee-Info-Panel.png
  docs/images/ui-screenshots/Employee-List-Panel.png
  docs/images/ui-screenshots/display-panel.png
Labels: priority.High, type.Documentation
